name: Deploy and Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Adjust the version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build and Run
        run: |
          node index.js &
      - name: Deploy page
        uses: actions/deploy-pages@v2
        with:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
